name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  provider: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets: 
  - Images/logojapa.png.png
  - Images/sashimi.png
  - Images/temaki.png
  - Images/yakissoba.png
  - Images/bebidas.png
  - Images/avatar.png
  - Images/combinado01.jpeg
  - Images/combinado02.jpeg
  - Images/combinado03.jpeg
  - Images/combinado04.jpeg
  - Images/kanimaki.jpeg
  - Images/kapamaki.jpeg
  - Images/sakemaki.jpeg
  - Images/temaki_grelhado.jpeg
  - Images/temaki_frito.jpeg
  - Images/temaki_salmao.jpeg
  - Images/sashimi_salmao.jpeg
  - Images/sashimi_branco.jpeg
  - Images/niguiri_salmao.jpeg
  - Images/niguiri_camarao.jpeg
  - Images/niguiri_branco.jpeg
  - Images/yakissoba_misto.jpeg
  - Images/yakissoba_frango.jpeg
  - Images/yakissoba_carne.jpeg
  - Images/gohan.jpeg
  - Images/tempura.jpeg
  - Images/banana.jpeg
  - Images/goiabada.jpeg
  - Images/guarana.png
  - Images/coca_cola.png
  - Images/h2o.jpeg
  - Images/agua01.jpeg
  - Images/agua02.jpeg
  - Images/suco_uva.jpeg
  - Images/suco_maracuja.jpeg